spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

  jpa:
    hibernate:
      ddl-auto: update

admin:
  user: ${ADMIN_USER}
  first-name: ${ADMIN_FIRST_NAME}
  last-name: ${ADMIN_LAST_NAME}
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
